// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/4/2026, 3:52:37 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/app/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/app/plugins/**/*.{js,ts,mjs}","/app/app/composables/**/*.{js,ts,mjs}","/app/app/utils/**/*.{js,ts,mjs}","/app/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/app/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/app/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;